---
- hosts: localhost
  connection: local
  name: OME Device Discovery
  gather_facts: False
  vars:
    hostname: 
    username: 
    password: 
    idrac_ip: ""
    hostname: ""
  tasks:
    - ome_discovery:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        #schedule_cron: "0 0 0 * * ? *" # Daily
        name: "{{ hostname }}"
        discover_range: 
          - "{{ idrac_ip }}"
        discover_username: ""
        discover_password: ""
        trap_destination: False
        device_type: "server"
